/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RpcRouteImport } from './routes/rpc'
import { Route as ReadRouteImport } from './routes/read'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _ratSplatRouteImport } from './routes/__rat.$'

const RpcRoute = RpcRouteImport.update({
  id: '/rpc',
  path: '/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _ratSplatRoute = _ratSplatRouteImport.update({
  id: '/__rat/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/read': typeof ReadRoute
  '/rpc': typeof RpcRoute
  '/$': typeof _ratSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/read': typeof ReadRoute
  '/rpc': typeof RpcRoute
  '/$': typeof _ratSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/read': typeof ReadRoute
  '/rpc': typeof RpcRoute
  '/__rat/$': typeof _ratSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/read' | '/rpc' | '/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/read' | '/rpc' | '/$'
  id: '__root__' | '/' | '/read' | '/rpc' | '/__rat/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadRoute: typeof ReadRoute
  RpcRoute: typeof RpcRoute
  _ratSplatRoute: typeof _ratSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rpc': {
      id: '/rpc'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof RpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__rat/$': {
      id: '/__rat/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof _ratSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadRoute: ReadRoute,
  RpcRoute: RpcRoute,
  _ratSplatRoute: _ratSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
