import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
const outputPath = fileURLToPath(
  new URL("../src/bundled-content.generated.ts", import.meta.url)
);

const [agentLaw, learnRatStackSource] = await Promise.all([
  readFile(`${repoRoot}AGENTS.md`, "utf-8"),
  readFile(`${repoRoot}skills/learn-rat-stack/SKILL.md`, "utf-8"),
]);

const output = `// Generated by scripts/generate-content.ts. Do not edit by hand.\nexport const agentLaw = ${JSON.stringify(agentLaw)};\n\nexport const learnRatStackSource = ${JSON.stringify(learnRatStackSource)};\n`;

await writeFile(outputPath, output);
